#!/bin/bash

#Functions
helpCommand () {
    echo "gsudo v$VERSION"
    echo "------------------------------------------------------------"
    echo "Usage: gsudo application"
    echo "       gsudo application {options}"
    printf "\n"
    echo "Options:"
    echo "None at the moment."
}

aboutCommand () {
    echo "gsudo v$VERSION"
    echo "------------------------------------------------------------"
    echo "Author: dolfies"
    echo "A simple script that runs GUI applications with root access."
    printf "\n"
    echo "https://github.com/dolfies/gsudo"
}

#Variables
application=$1
commandLine=$@
VERSION=1.2.1

#Help Command
if [[ "$1" == "--help" || "$1" == "-?" || "$#" -eq 0 ]]; then
    helpCommand
    exit
fi

#About Command
if [[ "$1" = "--about" || "$1" = "-a" ]]; then
    aboutCommand
    exit
fi

#Run Command
echo "Launching $application..."
DUMMY=$(sudo sh -c "sudo pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true $commandLine >/dev/null 2>&1 &")
